### ISSUE TITLE
linux 运行出错

### ISSUE THREAD

**Issue by ocoj** [yfyhboy/Aliyun-DDNS-shell#2]
运行提示以下出错信息，
ERROR: SDK.ServerError
ErrorCode: DomainRecordDuplicate
Recommend: https://next.api.aliyun.com/troubleshoot?q=DomainRecordDuplicate&product=Alidns
RequestId: 7092A468-B84D-5076-A1A0-C2C96D09B156
Message: The DNS record already exists.
RespHeaders: map[Access-Control-Allow-Headers:[X-Requested-With, X-Sequence, _aop_secret, _aop_signature, x-acs-action, x-acs-version, x-acs-date, Content-Type] Access-Control-Allow-Methods:[POST, GET, OPTIONS, PUT, DELETE] Access-Control-Allow-Origin:[*] Access-Control-Max-Age:[172800] Connection:[keep-alive] Content-Length:[251] Content-Type:[application/json;charset=utf-8] Date:[Fri, 09 Sep 2022 01:33:26 GMT] X-Acs-Request-Id:[7092A468-B84D-5076-A1A0-C2C96D09B156] X-Acs-Trace-Id:[d0c4839311a95a06c6345a73b572a57e]]

**Comment by yfyhboy** [comment]
把阿里云里面已创建的解析删掉试试

**Comment by yfyhboy** [comment]
close
