### ISSUE TITLE
这是哪里错了

### ISSUE THREAD

**Issue by 3032028472** [yfyhboy/Aliyun-DDNS-shell#3]
解压
tar (child): aliyun-cli-linux-latest-amd64.tgz：无法 open: 没有那个文件或目录
tar (child): Error is not recoverable: exiting now
tar: Child returned status 2
tar: Error is not recoverable: exiting now
复制到系统文件夹
cp: 无法获取"aliyun" 的文件状态(stat): 没有那个文件或目录
cli初始化设置
./aliyunDDNS.sh:行46: aliyun: 未找到命令
安装阿里云cli结束
本地IP地址：2409:8a30:2ea1:d6f0:8830:b9ff:fe85:84b1
读取阿里云解析记录：y.xwzjboke.xyz
./aliyunDDNS.sh:行69: /root/aliyun: 没有那个文件或目录
读取到解析记录：
读取到recordid：
未找到有效记录，准备添加记录。。。
添加解析记录：y.xwzjboke.xyz，2409:8a30:2ea1:d6f0:8830:b9ff:fe85:84b1
./aliyunDDNS.sh:行81: aliyun: 未找到命令
返回ID：
添加解析记录失败！
[root@centos Aliyun-DDNS-shell-main]#

**Comment by yfyhboy** [comment]
没有找到文件，应该是压缩包没有下载下来，可能是执行脚本时机器没有上网

**Comment by yfyhboy** [comment]
close
